# Introducción, objetivos y contenido

* Importación de librerías
* Carga de datos
* Funcionamiento del modelo seleccionado

# Importación de librerías

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Carga de datos

In [2]:
df_mlo = pd.read_csv('df_mlo.csv',index_col=False)
df_mlo = df_mlo.drop(columns=['Unnamed: 0'])

df_mlo.sample(2)

item_id  genre_id  year  price  playtime_acc  recommend  polarity  \
55     343360         2  2015   0.99      100550.0          1  0.136364   
1390      550         1  2009  19.99   101191416.0          1  0.160000   

      sentiment  
55            2  
1390          2

In [3]:
# Calcular la similitud del coseno entre las filas del DataFrame
cosine_sim = cosine_similarity(df_mlo)

# Mostrar la matriz de similitud del coseno
random_indices = np.random.choice(cosine_sim.shape[0], size=5, replace=False)  # Obtener 5 índices aleatorios
random_sample = cosine_sim[random_indices, :]  # Seleccionar las filas correspondientes a los índices aleatorios
print("Muestra aleatoria de la matriz de similitud del coseno:")
print(random_sample)

Muestra aleatoria de la matriz de similitud del coseno:
[[0.99986065 0.99999926 0.99174687 ... 0.07156602 0.99997354 0.99923103]
 [0.99988894 0.99999551 0.99197357 ... 0.07334183 0.99998478 0.99929941]
 [0.99985232 0.99999976 0.99168681 ... 0.07110033 0.99997011 0.99921225]
 [0.56074033 0.54588376 0.6496763  ... 0.87414365 0.55291924 0.57926139]
 [0.99984026 1.         0.99159788 ... 0.07041275 0.99996454 0.99918466]]


In [4]:
print(cosine_sim.shape)

(2000, 2000)
