# Introducción, objetivos y contenido

# Importación de librerías

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from math import factorial
from scipy import stats as st
import json
import gzip
import ast
from pandas import json_normalize
from textblob import TextBlob
import re
from sklearn.metrics.pairwise import cosine_similarity




# Carga de datos

In [9]:
df_mlo = pd.read_csv('df_mlo.csv',index_col=False)
df_mlo = df_mlo.drop(columns=['Unnamed: 0'])

df_mlo.sample(2)

item_id  genre_id  year  price  playtime_acc  recommend  polarity  \
631    202750         1  2012   9.99      169314.0          1  0.054164   
1198   232090         1  2016  29.99     7250241.0          1  0.042045   

      sentiment  
631           2  
1198          2

In [10]:
# Calcular la similitud del coseno entre las filas del DataFrame
cosine_sim = cosine_similarity(df_mlo)

# Mostrar la matriz de similitud del coseno
random_indices = np.random.choice(cosine_sim.shape[0], size=5, replace=False)  # Obtener 5 índices aleatorios
random_sample = cosine_sim[random_indices, :]  # Seleccionar las filas correspondientes a los índices aleatorios
print("Muestra aleatoria de la matriz de similitud del coseno:")
print(random_sample)

Muestra aleatoria de la matriz de similitud del coseno:
[[0.99953745 0.99883705 0.99668118 ... 0.11841998 0.9992076  0.99996896]
 [0.88650912 0.87812214 0.93263394 ... 0.53907729 0.88211981 0.89671552]
 [0.54443366 0.52939721 0.63469365 ... 0.88353904 0.5365224  0.56320557]
 [0.99984041 1.         0.99159893 ... 0.07042085 0.99996461 0.99918499]
 [0.98239691 0.978913   0.99711306 ... 0.27269839 0.98059847 0.98635886]]


In [11]:
print(cosine_sim.shape)

(2000, 2000)


In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Leer el DataFrame
df_mlo = pd.read_csv('df_mlo.csv')

# Calcular la similitud del coseno entre las filas del DataFrame
def calcular_similitud_coseno(df):
    features = df.drop(columns=['item_id'])  # Seleccionar solo las características para el cálculo de similitud
    cosine_sim = cosine_similarity(features, features)
    return cosine_sim

# Función de recomendación de juegos
def recomendacion_juego(item_id, df, cosine_sim):
    # Obtener el índice del juego de entrada en el DataFrame
    idx = df[df['item_id'] == item_id].index[0]
    
    # Obtener las puntuaciones de similitud del juego de entrada con otros juegos
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    # Ordenar los juegos por su similitud
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Seleccionar los 5 juegos más similares (excluyendo el juego de entrada)
    sim_scores = sim_scores[1:6]
    
    # Obtener los índices de los juegos recomendados
    juego_indices = [i[0] for i in sim_scores]
    
    # Devolver los item_id de los juegos recomendados
    return df.iloc[juego_indices]['item_id'].tolist()

# Ejemplo de uso de la función de recomendación
item_id_entrada = 232090  # ID de juego de entrada
cosine_sim = calcular_similitud_coseno(df_mlo)
juegos_recomendados = recomendacion_juego(item_id_entrada, df_mlo, cosine_sim)
print("Juegos recomendados para el juego con ID", item_id_entrada, ":", juegos_recomendados)
