# Introducción, objetivos y contenido

# Importación de librerías

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from math import factorial
from scipy import stats as st
import json
import gzip
import ast
from pandas import json_normalize
from textblob import TextBlob
import re
from sklearn.metrics.pairwise import cosine_similarity

# Carga de datos

In [2]:
df_mlo = pd.read_csv('df_mlo.csv',index_col=False)
df_mlo = df_mlo.drop(columns=['Unnamed: 0'])

df_mlo.sample(2)

item_id  genre_id  year  price  playtime_acc  recommend  polarity  \
1316   219150         1  2012   9.99     2658682.0          1      -0.2   
1634    42700         1  2010  39.99     8616029.0          0       0.0   

      sentiment  
1316          0  
1634          1

In [3]:
# Calcular la similitud del coseno entre las filas del DataFrame
cosine_sim = cosine_similarity(df_mlo)

# Mostrar la matriz de similitud del coseno
random_indices = np.random.choice(cosine_sim.shape[0], size=5, replace=False)  # Obtener 5 índices aleatorios
random_sample = cosine_sim[random_indices, :]  # Seleccionar las filas correspondientes a los índices aleatorios
print("Muestra aleatoria de la matriz de similitud del coseno:")
print(random_sample)

Muestra aleatoria de la matriz de similitud del coseno:
[[0.99997843 0.999936   0.99299586 ... 0.08167572 0.99999566 0.99957732]
 [0.67719829 0.6639796  0.75512845 ... 0.79264706 0.67025274 0.69361482]
 [0.99796105 0.99666142 0.9988354  ... 0.15150198 0.9973126  0.99914415]
 [0.99998576 0.99992123 0.99314145 ... 0.08291024 0.99999133 0.99961256]
 [0.99984155 0.99999972 0.99160172 ... 0.070442   0.99996451 0.99918647]]


In [4]:
print(cosine_sim.shape)

(2000, 2000)
